<Project Sdk="LibreWPF.Sdk/0.1.0-preview.29">
  <PropertyGroup>
    <TargetFramework>$(ProGpuWpfSdkSampleTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>ICSharpCode.WpfDesign</AssemblyName>
    <RootNamespace>ICSharpCode.WpfDesign</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>12.0</LangVersion>
    <Nullable>disable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\ICSharpCode.SharpDevelop.snk</AssemblyOriginatorKeyFile>
    <DefineConstants>$(DefineConstants);LIBREWPF</DefineConstants>
    <NoWarn>$(NoWarn);1591;CS1591;CS0618;SYSLIB0050;SYSLIB0051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**" />
    <Compile Include="..\..\GlobalAssemblyInfo.cs" Link="GlobalAssemblyInfo.cs" />
  </ItemGroup>
</Project>
